language: python

sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
    - xvfb
    - firefox

env:
  global:
    - COLAB_SETTINGS=tests/colab_settings.py

install:
  - pip install coveralls flake8 behave behave_django selenium
  - pip install .

script:
  - python setup.py test
  - xvfb-run -a colab-admin behave --format=progress
  - flake8 colab

after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#colab"
    on_success: change
    on_failure: always
    use_notice: true
