language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.7.3

install:
  - pip install django==${DJANGO_VERSION}
  - pip install .
  - psql -c "CREATE USER colab WITH PASSWORD 'colab' CREATEDB;" -U postgres

before_script:
  flake8 colab

script:
  python setup.py test

after_success:
  coveralls
