language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.7.3

install:
  - pip install -r requirements_test.txt
  - pip install django==${DJANGO_VERSION}
  - pip install -e .
  - colab-init-config > settings.yaml
  - sudo mkdir -p /etc/colab/
  - sudo cp settings.yaml /etc/colab/
  - psql -c "CREATE USER colab WITH PASSWORD 'colab' CREATEDB;" -U postgres

#before_script:
#  flake8 revproxy

script:
  ./runtests.py

#after_success:
#  coveralls
